### ISSUE TITLE
Please setup pull bot for this repo

### ISSUE THREAD

**Issue by rafsanulhasan** [aalok05/CodeHub#116]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Question
[x] Repo feature request
```

## Current behavior
No pull

## Expected behavior
Please configure [pull bot](https://github.com/wei/pull) so that we, contributors, can automatically merge from from upstream

**Comment by aalok05** [comment]
Not sure if we really need this right now. So closing it.

**Comment by rafsanulhasan** [comment]
It's up to you. But IMHO we need this because when you make any commit to master (which is default) branch, its been automatically merged by pull bot for my forked repo. It's so helpful. If any developer wants to merge changes in the dev branch also, they can do it using this pull bot. It'll help devs who are working in dev branch can have the changes merged into the branch automatically when anyone commit to this branch. Perhaps, this is really so much useful for the contributors. The rest is up to you.
