### ISSUE TITLE
App should run at windows startup

### ISSUE THREAD

**Issue by rafsanulhasan** [aalok05/CodeHub#123]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Question
```

## Expected behavior
App should run at windows startup

**Comment by aalok05** [comment]
I think this should be an option in settings, if at all people want this.

**Comment by rafsanulhasan** [comment]
Actually in my view, it seems that it is a needed feature for background tasks to show notification, otherwise it might not be needed

**Comment by aalok05** [comment]
If you are working on this, I'll merge your branch into a feature branch and keep it for future release.

**Comment by rafsanulhasan** [comment]
Yes, I'm working on this, but did not created a pull request for it yet.
