### ISSUE TITLE
Trending Pivot slide gesture

### ISSUE THREAD

**Issue by rootasjey** [aalok05/CodeHub#22]
Hello,
First of all, good work for this app.

It seems that I can't slide horizontally on the trending view to change PivotItem.
For example, from 'today' to 'this week'.

This issue happens when I'm on phone (Lumia 650).
I'll try to look into this issue this weekend.

**Comment by aalok05** [comment]
Hey! I actually thought I fixed this one by doing this 
`<userControls:RepoListItem ManipulationMode="System" />`
But turns out it is still a problem. Not sure why.

**Comment by rootasjey** [comment]
It seems that this property (on PullToRefreshListView) is blocking touch manipulations:
`IsPullToRefreshWithMouseEnabled="True"`

I don't know which action you'd like to take:

- Deactivate this option
- Deactivate this option only on mobile devices
- Try to manually handle touch manipulations on PullToRefreshListView

I wonder if this is the PullToRefreshListView's correct behavior or a bug.

**Comment by aalok05** [comment]
Thanks for the analysis. I'll try the second option (Deactivate this option only on mobile devices), could you also try it and test it on a mobile device? (I do my testing on an emulator).
It does not seem like the ideal behaviour though.

**Comment by rootasjey** [comment]
You welcome 😊 
Yes, I will be able to test the fix on my device. For now, when the property is deactivated I'm able to slide horizontally to change PivotItem (today, week, month).

**Comment by aalok05** [comment]
test

**Comment by aalok05** [comment]
test

**Comment by aalok05** [comment]
**testing comments in CodeHub**

**Comment by aalok05** [comment]
I'm disabling `IsPullToRefreshWithMouseEnabled` property for now so users will be able to slide horizontally
