### ISSUE TITLE
Strings to Translate

### ISSUE THREAD

**Issue by aalok05** [aalok05/CodeHub#25]
These English strings need to be translated to **Chinese** ,**German**, **Vietnamese** and **Portuguese**

- Create
- Cancel
- New Issue
- Labels
- Comment
- Body
- Title
- Activity
- Clone
- Share
- Releases
- Released by
- Contributors
- No open Pull Requests
- No closed Pull Requests

**Comment by brullsker** [comment]
Hey! Here you go with the German translation:

Create -> Erstelle
Cancel -> Abbrechen
New Issue -> Neues Problem
Labels -> Labels
Comment ->Kommentieren
Body -> Rumpf
Title -> Titel

Yours, Jakob H.

**Comment by aalok05** [comment]
@brullsker Great!

**Comment by brullsker** [comment]
Activity -> Aktivität
Clone -> Klonen
Share -> Teilen
Releases -> Veröffentlichungen
Released by -> Veröffentlicht von
Contributors -> Mitarbeiter
No open Pull Requests -> Keine offenen Aufnahmeanträge
No closed Pull Requests -> Keine angenommenen Aufnahmeanträge

Greetings, Jakob H

**Comment by aalok05** [comment]
@brullsker I've created https://github.com/aalok05/CodeHub/issues/32 for better tracking of which strings have been translated. It'll be easier for translators. 👍
