### ISSUE TITLE
Click/tap items in the notifications

### ISSUE THREAD

**Issue by mattleibow** [aalok05/CodeHub#26]
It would be awesome to be able to tap an item, such as an issue comment, in the notifications view. The was I can get there without having to manually go to the repo and then the issues tab.

**Comment by aalok05** [comment]
That would be great @mattleibow . I'll figure this out soon.

**Comment by aalok05** [comment]
Notifications do not contain 'payload' field so we can't navigate to specific issue/PR as of now (Octokit.net limitation), but we can navigate to repository -> af0878f
Clicking on New feed Items will navigate us to issue/repo/PR -> 93fa1b3
