### ISSUE TITLE
UI improvements on Issues page

### ISSUE THREAD

**Issue by brullsker** [aalok05/CodeHub#27]
I think, taking the pivot header up (as you can see in the attached picture) would look much better.
![2017-14-6--12-42-13](https://user-images.githubusercontent.com/22963301/27132952-e284c6dc-5110-11e7-8bf0-6eeac88b31a8.jpeg)

**Comment by brullsker** [comment]
And nearly the same thing is moving the "Refresh" button on Notifications page up to the header

**Comment by aalok05** [comment]
The pivot header takes the whole row so positioning the New Issue button beside it is gonna be a problem. But I can place it somewhere better so that two rows aren't been used.

**Comment by aalok05** [comment]
3461bc3 fixes this.
