### ISSUE TITLE
Add language selection

### ISSUE THREAD

**Issue by brullsker** [aalok05/CodeHub#28]
Appearance settings might be the right place for an option like this.

**Comment by aalok05** [comment]
I think General settings would be appropriate. I will think on implementing this.

**Comment by aalok05** [comment]
@PoLaKoSz nope.

**Comment by PoLaKoSz** [comment]
@aalok05 Where sould I put this option inside the Settings? `Appearance`?
Is it enough if the changes made effect after the application restart?

**Comment by aalok05** [comment]
@PoLaKoSz I think General settings would be a good place for language options, and yes it is fine if changes take place after app restart.

**Comment by aalok05** [comment]
PR #99 adds this feature.
