### ISSUE TITLE
Its possible to edit new issues while publishing them

### ISSUE THREAD

**Issue by brullsker** [aalok05/CodeHub#29]
After I tapped on "Create", the "Creating..." text appears, but I'm still able to tap into the text boxes and write into them.
I'll publish a pic of it as soon as possible.
![p4opo_20170614_16_47_19](https://user-images.githubusercontent.com/22963301/27138704-617450e2-5121-11e7-8501-600f00454b33.jpg)
I hope you can get my point by looking on this pic.

**Comment by aalok05** [comment]
That's a good catch. Fixing asap!

**Comment by aalok05** [comment]
0303fdf fixes this.
