### ISSUE TITLE
Strings to Translate

### ISSUE THREAD

**Issue by aalok05** [aalok05/CodeHub#32]
|   |  German | Chinese  | Vietnamese  | Portuguese  |
|---|---|---|---|---|
|Whats New |   |   |   |   |
|Edit Issue  |   |   |   |   |
|Special Thanks  |   |   |   |   |
|What's new in this version?  |   |   |   |   |
|Check for Notifications frequently  |   |   |   |   |
| Turning this on will consume more data |   |   |   |   |
| Mark all as read |   |   |   |   |
| owned | :white_check_mark:  |   |   |   |
| Save | :white_check_mark:  |   |   |   |
| Create  |  :white_check_mark: |   |   |   |
| Cancel  | :white_check_mark: |   |   |   |
| New Issue  | :white_check_mark:  |   |   |   |
| Labels  | :white_check_mark: |   |   |   |
| Comment  | :white_check_mark:  |   |   |   |
| Body  | :white_check_mark:  |   |   |   |
| Title  | :white_check_mark:  |   |   |   |
| Activity  | :white_check_mark:  |   |   |   |
| Clone  | :white_check_mark:  |   |   |   |
| Share  | :white_check_mark:  |   |   |   |
| Releases  | :white_check_mark: |   |   |   |
| Released by  | :white_check_mark:  |   |   |   |
| Contributors  | :white_check_mark:  |   |   |   |
| No open Pull Requests  | :white_check_mark: |   |   |   |
| No closed Pull Requests  | :white_check_mark:  |   |   |   |
| Blur content behind window  |  :white_check_mark:   |   |   |   |

**Comment by brullsker** [comment]
German: Blur content behind window -> Inhalt hinterm Fenster mit Blur-Effekt anzeigen

**Comment by PoLaKoSz** [comment]
I'm a hungarian beginner developer so if you want I can try to translate the English words to hungarian.

**Comment by aalok05** [comment]
Hey @PoLaKoSz 
Sure, you can take the Strings/en-US/Resource.resw file and create a new Resource file with all Hungarian strings. You can mail me this file so I can add it in the repo.

**Comment by brullsker** [comment]
German:
owned -> Eigene
Save -> Speichern

**Comment by brullsker** [comment]
Hey @aalok05 
I've updated the German resources file. You can find it here: [https://1drv.ms/u/s!Ah_MAaR2jd8u9w_KlUy75oOV0a5u](url)
Greetings, Jakob H

**Comment by aalok05** [comment]
Hey @brullsker , the link is broken.

**Comment by Darkpingouin** [comment]
@aalok05 if you want I can take care of the french translation

**Comment by aalok05** [comment]
@Darkpingouin That would be great. Go ahead!

**Comment by brullsker** [comment]
de-De
What's new -> Was ist neu?
Edit Issue -> Problem bearbeiten
Special Thanks -> Danksagungen
What's new in this version? -> Neuigkeiten in dieser Version
Check for Notifications frequently -> Regelmäßig nach neuen Benachrichtigungen suchen
Turning this on will consume more data  -> Bei Aktivierung dieser Option werden mehr Daten verbraucht
Mark all as read -> Alle als gelesen markieren

**Comment by aalok05** [comment]
There are a lot of untranslated strings now, it's hard to keep track so I'll leave it up to translators who wish to dig into the resource files. I'll close this for now.
