### ISSUE TITLE
Hamburger menu custom acrylic brush doesn't switch source when in expanded UI

### ISSUE THREAD

**Issue by Sergio0694** [aalok05/CodeHub#35]
As seen in the screenshot, the hamburger menu effect should switch from the in-app blur to the background blur when the app UI is in the extended mode, as otherwise there's no in-app content to blur and the whole effect becomes useless.

![image](https://user-images.githubusercontent.com/10199417/27760687-0ebeb04c-5e4e-11e7-8464-e35fbf7ace01.png)

**Comment by aalok05** [comment]
Hey @Sergio0694 , I'm having an issue with this. On state change of Window, when I change the background of Hamburger menu to acrylic brush, there is an issue wherein the screen flickers and the host blur stops working after that. I do dispose the existing in app blur effect.

**Comment by Sergio0694** [comment]
@aalok05 Wait, why are you talking about disposing the effect manually? I thought you were using the `CustomAcrylicBrush` class. With that, you could just bind the `Mode` property to be able to switch between in-app and background blur when needed.

**Comment by aalok05** [comment]
I check the build, and for unsupported builds I use normal blur effect which needs to be disposed.

**Comment by aalok05** [comment]
Anyway the switching causes a flicker in my laptop screen that lasts a few seconds...maybe I am doing something wrong.

**Comment by Sergio0694** [comment]
Mh, I'm not sure, I'll take a look at the code when I have some time, could you link the exact line/file where you switching the effects?

**Comment by aalok05** [comment]
Here it is 31c0f3a5e6abe5b06b6f750c4887d3f0725aa2dc , I've created a separate branch for this
