### ISSUE TITLE
Hide readme pivot page for empty readme files / private repos

### ISSUE THREAD

**Issue by Sergio0694** [aalok05/CodeHub#36]
Right now, opening a repo page for a repo with no readme, or an empty readme file, or a private repo that has a blocked readme, you just get a blank `WebView` that just wastes space.
The whole pivot page should be hidden in these situations to save screen space.

**Comment by aalok05** [comment]
1052d60f88ca7601bb342e19b3c2dac85aa6331a takes care of this.

**Comment by Sergio0694** [comment]
@aalok05 Great 👍 
Anyways, next time you have a commit that fixes an issue, make sure to include "fixes #issuenumber" in the commit message, so that GitHub will automatically reference the issue from the commit.
See [**the guide here**](https://help.github.com/articles/closing-issues-via-commit-messages/).
