### ISSUE TITLE
Add a way to scroll/expand the readme when the screen height is too low

### ISSUE THREAD

**Issue by Sergio0694** [aalok05/CodeHub#37]
As shown in the image above, when the screen height is too low (for example on a mobile phone, when in landscape mode), it's really difficult to scroll and read the readme.
Possible solutions:
* Add a button to make the readme temporarily full screen
* Make the readme full size and let the whole page scroll (beware of the height of the content inside the `WebView` that's difficult to manage)
* Add an animation to increase the height of the `WebView` when scrolling down the whole page
* ...?

![image](https://user-images.githubusercontent.com/10199417/27763810-2b0335ec-5e8b-11e7-8404-ebca37f9779d.png)

**Comment by aalok05** [comment]
The third suggestion seems the best, I'll try to figure out parallax scrolling for this scenario, so that the top part of the page collapses when scrolled down.

**Comment by Sergio0694** [comment]
I guess you could achieve that if you set the upper padding of the WebView to the height of the page header, and then make it so the page header has a non-transparent background that covers the first (empty) part of the `WebView`. Just be advised that working with a `ScrollViewer` inside a `WebPage` control can be difficult as it doesn't work exactly like a standard `ScrollViewer`.
