### ISSUE TITLE
The user avatar shape on the "contributors" pane is different.

### ISSUE THREAD

**Issue by kumarharsh** [aalok05/CodeHub#42]
Its rounded rectangle instead of a circle.

**Comment by Sergio0694** [comment]
@aalok05 I guess this is a design choice and not an oversight, but take a look into it just in case

**Comment by aalok05** [comment]
This is a design choice. User List items throughout the app have rounded rectangles. If I get more feedback in favor of circles, I'll go for circles when UWP community Toolkit comes out with RoundImageEx control in v 1.5

**Comment by kumarharsh** [comment]
OK. I see. Although all other places have circles, so I assumed it was an oversight. Plus, many corporate logos get cut-off when circle is used for avatar.

**Comment by aalok05** [comment]
@kumarharsh that is true, maybe we'll use rounded rectangles for all avatars in the future.
