### ISSUE TITLE
Login fail: Can't connect to service

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#44]
**When I click the Sign In button here ....**

![login](https://user-images.githubusercontent.com/1327533/27835296-b55cbef6-60da-11e7-91f2-46054c303f37.PNG)

**I get this response:**

![after oauth - copy](https://user-images.githubusercontent.com/1327533/27835035-a4d91102-60d9-11e7-9ad6-0f50deaf8e24.PNG)

I don't know this helpful, but with this exact problem I found this: [uwp-csharp-connect-sample #9](https://github.com/microsoftgraph/uwp-csharp-connect-sample/issues/9)

My GitHub account status: **Free**
Windows 10 Version **1703** Build **15063.0**
Internet Explorer **11** Version 11.0.15063.0 Update Version **11.0.40** ([KB4012204](https://go.microsoft.com/fwlink/?linkid=841655))

**Comment by PoLaKoSz** [comment]
Oh Jesus Christ why am I so dumb?
**Don't** set the **Authorization callback URL** to [http://localhost/](http://localhost/) when you [Register](https://github.com/settings/developers) the application.

**Comment by JMccormick264** [comment]
@PoLaKoSz what did you change the Callback URL to? I am having this same issue and I can't figure it out.

**Comment by PoLaKoSz** [comment]
@JMccormick264 Hi.
I think [that](https://github.com/aalok05/CodeHub/blob/master/CodeHub/Services/AuthService.cs#L19) is a magic string so Callback URL need to be `http://example.com/path`

**Comment by aalok05** [comment]
You can set any callback url you want in the dashboard, just make sure the same url is used [here](https://github.com/aalok05/CodeHub/blob/master/CodeHub/Services/AuthService.cs#L19)
