### ISSUE TITLE
Repository watch button bug

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#45]
- The watch icon is not in the correct position (not in the center).
 ![watch](https://user-images.githubusercontent.com/1327533/27888321-b88706ac-61e5-11e7-9036-31c1fb0e9469.png)
- Watched people count is not show the correct number (only the frontend buggy)

**Comment by PoLaKoSz** [comment]
Test comment

**Comment by aalok05** [comment]
Sometimes the API returns 0 in SubscriberCount field. I'll fix the position.

**Comment by PoLaKoSz** [comment]
I didn't open this issue to make you more work 😃 I just wanted to take a note about it so let me help to you.

**Comment by aalok05** [comment]
Sure man go ahead 😄
