### ISSUE TITLE
New issue button bug

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#46]
When I hover the New issue button a little rectangle appear in the background.
![new_issue](https://user-images.githubusercontent.com/1327533/27888705-c1dd0d62-61e7-11e7-97d6-a42d9580eabc.png)
If it is not a bug, maybe will be more prettier to change the button color when hovered.

**Comment by aalok05** [comment]
I'll do something about this.

**Comment by PoLaKoSz** [comment]
Let me try first because you better than me and you don't need to spend time with this tiny little bug so you can do more important things. What do you think?

**Comment by aalok05** [comment]
Yeah sure man! And thanks for the compliment 😄
