### ISSUE TITLE
Markdown Issue

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#47]
Markdown not converted to HTML inside a Issue.
![markdown](https://user-images.githubusercontent.com/1327533/27889404-79039598-61ec-11e7-975c-4a41523a85f8.PNG)

**Comment by aalok05** [comment]
Yup, this is an issue for UWP community toolkit, I am using their MarkdownTextblock control. This control has issues with big tables. Can you open an issue in the  UWP community toolkit repo?
