### ISSUE TITLE
UI issue on About page

### ISSUE THREAD

**Issue by brullsker** [aalok05/CodeHub#48]
**On "About" page:**
"Rate" and "Star on GitHub" buttons / texts are not on the same level as "Twitter" and "E-Mail" buttons / texts
![wp_ss_20170704_0001 2](https://user-images.githubusercontent.com/22963301/27907876-a62f50ea-6249-11e7-9ba0-f3ab08a6fe96.png)

Also, the "Star on GitHub" button needs a translation.
In German, it would be "Repo favorisieren".

**Comment by aalok05** [comment]
7c310f3a600c8a18c8c5e6b2804ffd7f6ba19786 fixes this
