### ISSUE TITLE
MyRepository/starred repositories count not load

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#53]
After clicking **MyRepository** menu the app
* load
  * the owned repositories
  * the owned repositories count
* not load
  * the starred repositories count
![myrepositorybug](https://user-images.githubusercontent.com/1327533/27954387-fde59aa8-630f-11e7-919b-3d8358496379.PNG)

Tomarrow I hope I can fix this.

**Comment by aalok05** [comment]
Actually this is designed to be so. Starred repos will only load when pPivotItem is changed. This behaviour is consistent throughout the app.

**Comment by PoLaKoSz** [comment]
Oh, okey.
