### ISSUE TITLE
When create a new PR

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#54]
I recognize I create a lot of PR but only 1-2 commits in it.
What is the best practice to avoid the lot of PR per day? Is somewhere an article about it?

**Comment by aalok05** [comment]
A PR should be concerned with only 1 feature/fix. Create a separate branch for a feature that you are working on, Name the branch 'feature_featureName', and when that feature is completed in your branch, create a PR for it.

**Comment by PoLaKoSz** [comment]
Thank you so much for your fast response.
I want to be 100% sure about this so I want to ask is that means my #52 PR is not well executed because I didn't separate the 2 fixes?

**Comment by aalok05** [comment]
Several fixes can be merged in a single PR, that's fine.

**Comment by PoLaKoSz** [comment]
Thank you. I will pay attention for this.
