### ISSUE TITLE
UI improvement on Notifications page

### ISSUE THREAD

**Issue by brullsker** [aalok05/CodeHub#67]
Nearly the same as in issue #27. Here a possible solution:
![wp_ss_20170721_0001](https://user-images.githubusercontent.com/22963301/28456194-c2447f08-6e01-11e7-8625-bb85f8ed5ef4.png)
As you can see, the Refresh button is placed like in #63, and the Mark all as read button like the New issue button on issues page.

**Comment by aalok05** [comment]
I'm thinking of moving the refresh and 'mark all as read' button to bottom of the page like a commandbar. This way we won't have to add a refresh button to HeaderPanel on the MainPage,
