### ISSUE TITLE
German

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#73]
Write a comment with the translation or commit to #72, please. Thanks 😄 🍺

## **Search**

|                | Status |
|----------------|:--:|
| All Languages |  ✅  |
| Reset |  ✅  |

## **Settings / Donate**

|                | Status |
|----------------|:--:|
| Donate to CodeHub on Patreon |  ✅  |

## **Settings / General**

|                | Status |
|----------------|:--:|
| Make any donation to enable the option to disable ads. |  ✅  |

## **Settings / About**

|                | Status |
|----------------|:--:|
| What's new in this version? |  ✅  |
| Developed by Aalok Singh |  ✅  |

## **Time Ago converter**

|                | Status |
|----------------|:--:|
| one second ago |  ✅  |
| seconds ago    |  ✅  |
| a minute ago   |  ✅  |
| minutes ago    |  ✅   |
| an hour ago    |  ✅   |
| hours ago      |  ✅   |
| a day ago      |  ✅  |
| days ago       |  ✅  |
| one month ago  |  ✅  |
| months ago     |  ✅  |
| one year ago   |  ✅  |
| years ago      |  ✅  |

**Comment by brullsker** [comment]
de-DE
one second ago -> eine Sekunde zuvor
seconds ago -> Sekunden zuvor
a minute ago -> eine Minute zuvor
minutes ago -> Minuten zuvor
a day ago-> einen Tag zuvor
days ago -> Tage zuvor
one month ago -> einen Monat zuvor
months ago -> Monate zuvor
one year ago -> ein Jahr zuvor
years ago -> Jahre zuvor

**Comment by PoLaKoSz** [comment]
Thank You 👍

**Comment by brullsker** [comment]
Oh, yeah, sorry.
an hour ago -> eine Stunde zuvor
hours ago -> Stunden zuvor

**Comment by PoLaKoSz** [comment]
Up

**Comment by brullsker** [comment]
Search
All languages -> Alle.Sprachen
Reset -> Zurücksetzen

Settings / Donate
Donate to CodeHub on Patreon -> Spende an CodeHub über Patreon

Settings / General
Make any donation to enable the option to disable ads. -> Spende etwas, um die Option zur Entfernung von Werbung freizuschalten.

Settings / About

What's new in this version? -> Neuigkeiten in dieser Version
Developed by Aalok Singh -> Entwickelt von Aalok Singh

**Comment by PoLaKoSz** [comment]
Thank You @brullsker!
