### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#74]
Write a comment with the translation or make a PR after #72 is merged to the `dev` branch, please. Thanks 😄 🍺

## **Search**

|                | Status |
|----------------|:--:|
| All Languages ||
| Reset ||

## **Settings / Donate**

|                | Status |
|----------------|:--:|
| Donate to CodeHub on Patreon ||

## **Settings / General**

|                | Status |
|----------------|:--:|
| Make any donation to enable the option to disable ads. ||

## **Settings / About**

|                | Status |
|----------------|:--:|
| What's new in this version? ||
| Developed by Aalok Singh ||

## **Time Ago converter**

|                | Status |
|----------------|:--:|
| one second ago ||
| seconds ago    ||
| a minute ago   | |
| minutes ago    ||
| an hour ago    ||
| hours ago      ||
| a day ago      ||
| days ago       ||
| one month ago  ||
| months ago     ||
| one year ago   ||
| years ago      ||

**Comment by aalok05** [comment]
There are a lot of untranslated strings now, it's hard to keep track so I'll leave it up to translators who wish to dig into the resource files. I'll close this for now.
