### ISSUE TITLE
Portuguese

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#76]
Write a comment with the translation or commit to #72, please. Thanks 😄 🍺

## **Search**

|                | Status |
|----------------|:--:|
| All Languages ||
| Reset ||

## **Settings / Donate**

|                | Status |
|----------------|:--:|
| Donate to CodeHub on Patreon ||

## **Settings / General**

|                | Status |
|----------------|:--:|
| Make any donation to enable the option to disable ads. ||

## **Settings / About**

|                | Status |
|----------------|:--:|
| What's new in this version? ||
| Developed by Aalok Singh ||

## **Time Ago converter**

|                | Status |
|----------------|:--:|
| one second ago ||
| seconds ago    ||
| a minute ago   | |
| minutes ago    ||
| an hour ago    ||
| hours ago      ||
| a day ago      ||
| days ago       ||
| one month ago  ||
| months ago     ||
| one year ago   ||
| years ago      ||

**Comment by GitMoDu** [comment]
Search - Procura

All Languages	- Todas as línguas
Reset - Repor

Settings / Donate - Configurações / Doações

Donate to CodeHub on Patreon - Fazer uma doação para o CodeHube no Patreon
Settings / General - Configurações / Geral

Make any donation to enable the option to disable ads. - Faz uma doação para ativar a opção de desligar a publicidade.

Settings / About - Configurações / Sobre

What's new in this version? - Novidades nesta versão
Developed by Aalok Singh - Desenvolvido por Aalok Singh

Time Ago converter - Conversor de tempo atrás

one second ago - há um segundo atrás
seconds ago - há uns segundos atrás
a minute ago - há um minuto atrás
minutes ago - há minutos atrás
an hour ago - há uma hora atrás
hours ago - há horas atrás
a day ago - há um dia atrás
days ago	- há dias atrás
one month ago - há um mês atrás
months ago - há meses atrás
one year ago - há um ano atrás
years ago - há anos atrás

**Comment by PoLaKoSz** [comment]
@GitMoDu Thank You so much.
