### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#78]
Write a comment with the translation or make a PR to the `dev` branch, please. Thanks 😄 🍺

## **Search**

|                | Status |
|----------------|:--:|
| All Languages ||
| Reset ||

## **Settings / Donate**

|                | Status |
|----------------|:--:|
| Donate to CodeHub on Patreon ||

## **Settings / General**

|                | Status |
|----------------|:--:|
| Make any donation to enable the option to disable ads. ||

## **Settings / About**

|                | Status |
|----------------|:--:|
| What's new in this version? ||
| Developed by Aalok Singh ||

## **Time Ago converter**

|                | Status |
|----------------|:--:|
| one second ago ||
| seconds ago    ||
| a minute ago   | |
| minutes ago    ||
| an hour ago    ||
| hours ago      ||
| a day ago      ||
| days ago       ||
| one month ago  ||
| months ago     ||
| one year ago   ||
| years ago      ||

**Comment by madcated** [comment]
Hi, can I work on this?

**Comment by PoLaKoSz** [comment]
Of course.
