### ISSUE TITLE
Donation status should be saved in app

### ISSUE THREAD

**Issue by brullsker** [aalok05/CodeHub#80]
When I start the app on slow connection, the option to disable ads on general settings looks like this:
![wp_ss_20170903_0001](https://user-images.githubusercontent.com/22963301/30001127-49e1a216-9084-11e7-8705-529cf5cc667b.png)
It shouldn't, because I made a donation.
After a while, the app takes me to the Trending page, and when I get to the general settings page again, it looks like this:
![wp_ss_20170903_0002](https://user-images.githubusercontent.com/22963301/30001136-88d34d3a-9084-11e7-88e7-1c9f86305f01.png)
I think it would be better if the app knows if I donated or not without checking to online.

**Comment by aalok05** [comment]
I'll make it so that the app only checks online once, and then store a bool setting value.
