### ISSUE TITLE
[Question/Feature Request] URL Schemes?

### ISSUE THREAD

**Issue by justadaniel** [aalok05/CodeHub#85]
Hi,

I was wondering if there were any URL schemes for CodeHub? I like to change the URL's in edge to have them open the apps I have installed instead.

**Comment by aalok05** [comment]
So this can be done where if you visit a repo in your browser, you can open the repo in CodeHub, and so on. I haven't implemented this but it's a good idea.

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation

**Comment by aalok05** [comment]
It turns out, to launch repo view in CodeHub when someone navigates to a github repository in edge, I need to own the github website. Other than that there is no custom uri for CodeHub and I cannot think of any use case for it.

**Comment by justadaniel** [comment]
Really? When I worked on iOS apps, we would just create a custom url scheme that replaces `https://` with `appname://` and parse the url to do what we want. So `codehub://github.com/<author>/<reponame>` or you could even remove the `github.com/` all together. Then that would take you to the repo.

**Comment by aalok05** [comment]
ok got it. This can be done. I'm on it.

**Comment by aalok05** [comment]
#87 Here you go.

**Comment by aalok05** [comment]
I'll update readme for this feature when it is complete

**Comment by justadaniel** [comment]
Alright awesome, thanks!

**Comment by aalok05** [comment]
This feature has been merged in `dev` branch. 
Examples:

- _codehub://repository/aalok05/codehub_
- _codehub://user/aalok05_
